### ISSUE TITLE
Add link to docs in input dialogs

### ISSUE THREAD

**Issue by katmratliff** [cbirdferrer/collatrix#10]
Suggest adding a link to the sections of the readme with more info on the inputs if you do not want to add any more information to the dialog boxes themselves (I see your response to [this issue](https://github.com/cbirdferrer/collatrix/issues/4) but agree with @evaristor that more information would be helpful here). Perhaps you can link to the help box, which currently does not work?

![image](https://user-images.githubusercontent.com/12630578/85752974-dbcc9e00-b6d9-11ea-813e-4c44f9b57862.png)
 
Note: submitting as part of a [JOSS review](https://github.com/openjournals/joss-reviews/issues/2328)

**Comment by cbirdferrer** [comment]
Hi! Thanks for the suggestion! I think that adding a hyperlink to the documentation within the input dialog box text is a great idea. However, after digging into the documentation and trying a few things it does not look like that is easily done. I will continue to look into ways to do this, but in the meantime I've added a message box with a hyperlink to the relevant section of the online documentation at the start of the tool.
