### ISSUE TITLE
TypeError:  read_csv () got an unexpected keyword argument 'prefix'

### ISSUE THREAD

**Issue by abaz-oceans** [cbirdferrer/collatrix#15]
Good afternoon , 

I am trying to run the CollatriX Main Function (python -m collatrix) with the following input below: 

yes Animal ID in folder name
no safety
no subset list

My goal is to get an output .csv file measured in pixels. However, when I finish selecting my folders (steps 4-6), I receive the following error message:
TypeError:  read_csv () got an unexpected keyword argument 'prefix'

I checked the package was up to date with the line of code listed on your wiki page (pip install collatrix --upgrade)(1.0.8), but the error still comes up. I am a beginner (new) python user, and any help you could provide is appreciated. 

Thank you

**Comment by cbirdferrer** [comment]
Hi, can you provide a bit more information? If you could attach a screenshot of the terminal/command prompt window with the full error message and one of the morphometrix output csvs you're trying to collate, that would be great. Thanks!

**Comment by abaz-oceans** [comment]
Hi Clara, 

Thank you for your quick reply, I have attached the files below. 

[DJI_0026.csv](https://github.com/cbirdferrer/collatrix/files/11818569/DJI_0026.csv)
![CollatriX_Error](https://github.com/cbirdferrer/collatrix/assets/137197142/5f8bdde9-133b-4703-97cf-308010372669)

**Comment by cbirdferrer** [comment]
hi! thanks for providing that extra info. I think you have a newer version of the pandas package installed that what I developed collatrix in. In your terminal window try typing `pip install pandas==1.4.0` and running that, then try re-running collatrix. Hopefully that should do the trick!

**Comment by abaz-oceans** [comment]
Hi Clara, 

I was able to install the pandas package with the line of code that you recommended and re-run collatrix, but I received the same error (re: screenshot from above).

Thank you
![Screenshot 2023-06-27 135056](https://github.com/cbirdferrer/collatrix/assets/137197142/8008ab9a-0b5d-48c6-bb14-cdf38ad091f5)

**Comment by abaz-oceans** [comment]
Hi Clara - I am more than happy to make a time to meet virtually if it's easier to share my screen. I can send you an email with my contact information. 

Unfortunately, I received more error messages. It was too long to screenshot the whole output. I just included the top and bottom lines. 

![Screenshot 2023-06-29 151939](https://github.com/cbirdferrer/collatrix/assets/137197142/763d8936-3f44-4264-9545-faf07f89fb43)
![Screenshot 2023-06-29 152014](https://github.com/cbirdferrer/collatrix/assets/137197142/03bcb1f7-c983-4f8c-8b25-ccde7012d782)

**Comment by abaz-oceans** [comment]
Thanks for the patience and help Clara! This worked!!

1.	conda create –-name ccx python=3.8
2.	conda activate ccx
3.	pip install pyqt5==5.9.2 pandas==1.4.0 numpy==1.21.2
4.	Then the pip install for collatrix from github
5.	Then try running collatrix
