### ISSUE TITLE
[Beta V2 Feedback]

### ISSUE THREAD

**Issue by RiccardoCicciarella** [cbirdferrer/collatrix#18]
## System Information 

Operating System: Windows 11  
OS: nt  
Python version:  3.10.12

## Verify that you can carry out the following actions

Mark inside the brackets with an [x] to 

- [x] Wrangle LiDAR ([x] GPX or [ ] Fightware csv)
- [ ] Pull LiDAR for Videos
- [ ] Merge LiDAR for Videos
- [ ] Pull/Merge LiDAR for Images
- [x] Collate MorphoMetriX version 2 outputs
- [x] Calculate body condition metrics (list which metrics here: body volume (both ellipse and circle) and BAI (both parabola and trapeziod))

## If you encounter an error, please copy attach the crash log text file, any inputs you were trying to use, and any screenshots that might be helpful.

System: Windows
OS: nt
Python Version: 3.10.12
Python Implementation: CPython
Release: 10
Version: 10.0.22631
Machine: AMD64
Processor: Intel64 Family 6 Model 141 Stepping 1, GenuineIntel
Current Working DirectoryC:\Users\Riccardo\Desktop
CollatriX version: 2.0 beta

Traceback (most recent call last):
  File "collatrix\__main__.py", line 297, in <lambda>
  File "collatrix\__main__.py", line 545, in select_dir
IndexError: list index out of range

![image](https://github.com/cbirdferrer/collatrix/assets/138026487/2cb50054-3b8f-4e52-9b6d-f1cc5452a8fe)

I get this error when I select the folder in which I contain only the videos from the drone flight. I don't know exactly what "index out of range" would means. Maybe the fact that the format is MP4 instead of MOV (unfortunately I couldn't test it because I don't have the drone handy. If that's the case, I'd suggest making it compatible with other video formats).

Another error I get is when I click on "Exif Tag Viewer":

System: Windows
OS: nt
Python Version: 3.10.12
Python Implementation: CPython
Release: 10
Version: 10.0.22631
Machine: AMD64
Processor: Intel64 Family 6 Model 141 Stepping 1, GenuineIntel
Current Working DirectoryC:\Users\Riccardo\Desktop
CollatriX version: 2.0 beta

Traceback (most recent call last):
  File "collatrix\__main__.py", line 578, in open_exif_viewer
AttributeError: 'lidarvideoWindow' object has no attribute 'exif_tags'

It seems like it says that mt files have no attributes. I checked the properties, and even if some fields are missing, some of the key ones seem to be there (i.e. date created, date modified, length .etc):

![image](https://github.com/cbirdferrer/collatrix/assets/138026487/72dfc355-d729-4c2f-8a69-db53547fca86)
![image](https://github.com/cbirdferrer/collatrix/assets/138026487/38b16456-7144-4dcb-a4c0-72ffcc4fe0fe)
![image](https://github.com/cbirdferrer/collatrix/assets/138026487/5eb4cc4c-e4e0-4c58-8550-72bf4680e243)
![image](https://github.com/cbirdferrer/collatrix/assets/138026487/05bce97a-5637-4445-9d04-c62ff06cfacc)

## Please provide additional feedback and/or suggestions below
Thank you so much for your hard work! It's really a great tool! I like that it still does the basic functions and also could help to do more. 

In terms of suggestions, I'm just naively wondering if there is a way to simplify/reduce the amount of input needed to synchronize video and the altimeter .csv file.

**Comment by cbirdferrer** [comment]
hi! thanks for your patience, I think all of these errors come down to what you correctly suspected - its because in the code I filter for .MOVs - sorry! This causes downstream issues in the exiftool code, so it should work after I correct the .MOV only issue in the next release (should be published next week).
