### ISSUE TITLE
Automated tests are missing

### ISSUE THREAD

**Issue by evaristor** [cbirdferrer/collatrix#2]
There are no automated tests. I suggest using [pytest-qt](https://pytest-qt.readthedocs.io) (or [Qt Test](https://doc.qt.io/qt-5/qttest-index.html)) in conjunction with GitHub Actions or Travis. You can find more information here:

- [PyQt: GUI Testing](https://wiki.python.org/moin/PyQt/GUI_Testing)
- [Test PyQt GUIs with QTest and unittest](http://johnnado.com/pyqt-qtest-example/)

---

- [Review for the Journal of Open Source Software](https://github.com/openjournals/joss-reviews/issues/2328)

**Comment by cbirdferrer** [comment]
Hi! Thank you for this suggestion. We appreciate that automated testing would help improve our workflow. We have added an automated test through GitHub actions for the main function because this is the function that could be edited in the future if `MorphoMetriX` is updated. We also don’t anticipate the add-on functions being edited given that we intend for contributions to `CollatriX` to be in the form of new add-on functions.

**Comment by evaristor** [comment]
Thank you for addressing my suggestion. The use of GitHub Actions to run your tests automatically is a notable improvement of your software. Congratulations!

However, one of the most relevant parts of CollatriX is the GUI and, as of now, it is not tested.

I understand the reasons you provided for not testing extensively, and I even agree that those reasons are valid for a personal project. However, for an open-source project, a code coverage of 22% is quite low.

While trying to obtain a code coverage of 100% is impractical, it is customary to aim for anything between [70% and 80%](https://www.bullseye.com/minimum.html).

Since CollatriX is open-source software, I would encourage you to obtain a code coverage of al least 40%.

---

To verify the coverage of your code, you could use the command:

```
pytest --cov-config=.coveragerc --cov=collatrix --cov-report=term-missing --verbose
```

I encourage you to replace the last line of your `.github/workflows/testing.yml` file with that command.


Since your tests are in the `collatrix/` subdirectory, you will have to add the file `.coveragerc` to the root of the project with the following content:

```
[run]
omit = collatrix/tests/*
```

Finally, don't forget to add `pytest-cov` to line 26 of `.github/workflows/testing.yml`.

**Comment by cbirdferrer** [comment]
Hi! I appreciate the feedback. I've added the `.coveragerc` file and updated the `testing.yml`. I've looked into using `pytest-qt` to test the GUI functions. However, I've struggled to find good documentation or examples for using `pytest-qt` and `monkey patch` on the functions I use. I was wondering if you knew of any helpful examples or resources for testing `QInputDialog.getItem`, `QInputDialog.getText`, and `QInputDialog.getOpenFileName`?

**Comment by KristinaRiemer** [comment]
@evaristor I don't know if you have any suggestions for testing these functions for @cbirdferrer?

**Comment by evaristor** [comment]
@cbirdferrer @KristinaRiemer:

[This tutorial](https://pytest-qt.readthedocs.io/en/latest/tutorial.html) looks useful since it tests [this GUI](https://github.com/nicoddemus/PySide-Examples/blob/master/examples/dialogs/findfiles.py).

You could also get inspired by these code examples that use `QInputDialog`:

- [mworion/MountWizzard4/test_tabSettImaging.py](https://github.com/mworion/MountWizzard4/blob/5047dcc96a03279ae4c837477c8678ad4d5a3b76/mw4/test/unit_tests/gui/mainWmixin/test_tabSettImaging.py)
- [PacktPublishing/Hands-On-Blockchain-for-Python-Developers/advanced_course_qt/test_button_and_dialog.py](https://github.com/PacktPublishing/Hands-On-Blockchain-for-Python-Developers/blob/2513922b658fbf41d4c75678532d970553536ccb/Chapter09/advanced_course_qt/test_button_and_dialog.py)
- [psyplot/psy-view/test_ds_widget.py](https://github.com/psyplot/psy-view/blob/2ff170aa368f51d36c7d8a6c0b97e5cb841a9909/tests/test_ds_widget.py)
- [spyder-ide/spyder/test_breakpoints.py](https://github.com/spyder-ide/spyder/blob/0a83f097eed8b1e8ac77c7eaff289a07a69f0078/spyder/plugins/editor/widgets/tests/test_breakpoints.py)
- [teampheenix/StarCraft-Casting-Tool/test_gui.py](https://github.com/teampheenix/StarCraft-Casting-Tool/blob/072cea3f9ee198132a4cd19f439b76c09a01adcf/tests/test_gui.py)
- [wonambi-python/wonambi/test_widget_notes.py](https://github.com/wonambi-python/wonambi/blob/master/tests/test_widget_notes.py)

**Comment by cbirdferrer** [comment]
Thanks @KristinaRiemer!

Hi @evaristor, thank you for finding those examples! Your comments and suggestions have helped me improve the software and I greatly appreciate that! However, I’m wondering if adding further automated testing is necessary, especially since JOSS considers well-documented manual testing to be acceptable in the review criteria- https://joss.readthedocs.io/en/latest/review_criteria.html#tests

**Comment by evaristor** [comment]
Sounds good. Go ahead and close this issue.
It looks good. 👌🏾
