### ISSUE TITLE
Community guidelines

### ISSUE THREAD

**Issue by evaristor** [cbirdferrer/collatrix#3]
Please add a section in the README with guidelines for third parties wishing to 1) contribute to the software, 2) report issues or problems with the software, and 3) seek support.

---

- [Review for the Journal of Open Source Software](https://github.com/openjournals/joss-reviews/issues/2328)

**Comment by cbirdferrer** [comment]
Thank you! I've added a code of conduct and contributing guidelines files to the repo and added links to those files in the README.

**Comment by evaristor** [comment]
That looks good!
:+1: :100:
