### ISSUE TITLE
Commented-out code

### ISSUE THREAD

**Issue by evaristor** [cbirdferrer/collatrix#5]
Please remove the commented-out code. Lines 2 and 19 of setup.py and lines 6, 12, 16, and 17 of meta.yaml are commented out. You can find more information about why that is considered a bad idea here:

- [Please, don’t commit commented-out code](https://kentcdodds.com/blog/please-dont-commit-commented-out-code)
- [Don’t share commented-out code](https://www.nayuki.io/page/dont-share-commented-out-code)

---

- [Review for the Journal of Open Source Software](https://github.com/openjournals/joss-reviews/issues/2328)

**Comment by cbirdferrer** [comment]
Thank you for catching this! Those lines have been removed.

**Comment by evaristor** [comment]
There is still some unnecessary text in:
- [`requirements.txt`](https://github.com/cbirdferrer/collatrix/blob/master/requirements.txt)

**Comment by cbirdferrer** [comment]
Ah yes sorry, thank you for catching that! It's been removed.

**Comment by evaristor** [comment]
That looks good!
:+1: :100:
