### ISSUE TITLE
Build

### ISSUE THREAD

**Issue by evaristor** [cbirdferrer/collatrix#6]
Please show how to build the package. You could add a shell script, a Makefile, or a GitHub Actions (or Travis) configuration file that includes the command used to build the conda package.

---

- [Review for the Journal of Open Source Software](https://github.com/openjournals/joss-reviews/issues/2328)

**Comment by cbirdferrer** [comment]
It's a short script, but I've added a shell script to the repo containing the commands I use to build the package using `conda`.

**Comment by evaristor** [comment]
That looks good!
:+1: :100:
