### ISSUE TITLE
Output is not a valid CSV file

### ISSUE THREAD

**Issue by evaristor** [cbirdferrer/collatrix#7]
The header in column 1 of the output CSV file is blank. Please add a header to the first column of the output to ensure that it is a valid CSV file.

---

- [Review for the Journal of Open Source Software](https://github.com/openjournals/joss-reviews/issues/2328)

**Comment by cbirdferrer** [comment]
Thank you for this suggestion! Header added!

**Comment by evaristor** [comment]
Thank you for addressing this issue, but I'm still getting an empty header in the first column.

![image](https://user-images.githubusercontent.com/3461018/85800040-1f80d100-b6f5-11ea-882f-9b8a1c10762d.png)

You could also just remove the first column. In either case, I strongly recommend that the output be a valid CSV file.

If you believe that the problem is fixed and I'm missing something, please use an automated test to show this.

**Comment by cbirdferrer** [comment]
I apologize, I only changed one of the instances of `.to_csv` in the main function, I have double-checked that all instances (2 in the main function, 1 each in the other 2 functions) of `df.to_csv` now include an index_label: `.to_csv(outcsv,sep = ',',index_label = 'IX')`

**Comment by evaristor** [comment]
That looks good!
:+1: :100:
